# Generated by Django 4.2.13 on 2024-05-31 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Calendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("month", models.IntegerField()),
                ("day", models.IntegerField()),
                ("walkfinished", models.BooleanField(default=False)),
                ("question", models.CharField(blank=True, max_length=255, null=True)),
                ("sentence", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "emotion_large",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "emotion_small",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("first_name", models.CharField(blank=True, max_length=30)),
                ("last_name", models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="WalkHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("stable_score", models.FloatField()),
                ("stable_loc", models.CharField(max_length=255)),
                ("walk_score", models.FloatField()),
                ("distance", models.IntegerField()),
                ("course", models.CharField(max_length=255)),
                (
                    "calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="server.calendar",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SRI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sri_score", models.IntegerField()),
                ("sri_date", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="server.user"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="calendar",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="server.user"
            ),
        ),
    ]
