# Generated by Django 4.2.13 on 2024-06-01 01:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0001_initial"),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name="user",
        #     name="first_name",
        # ),
        # migrations.RemoveField(
        #     model_name="user",
        #     name="last_name",
        # ),
        migrations.AddField(
            model_name="user",
            name="nickname",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
