# Generated by Django 4.2.13 on 2024-06-15 22:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_admin",
        ),
    ]
