# Generated by Django 4.2.13 on 2024-06-01 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_remove_user_first_name_remove_user_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
