# Generated by Django 4.2.13 on 2024-06-01 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0002_alter_user_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
