# Generated by Django 4.2.13 on 2024-06-02 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_remove_user_first_name_remove_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walkhistory',
            name='distance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='walkhistory',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='walkhistory',
            name='stable_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='walkhistory',
            name='walk_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
