# Generated by Django 4.2.13 on 2024-06-02 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_alter_walkhistory_distance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walkhistory',
            name='course',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='walkhistory',
            name='stable_loc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='walkhistory',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
