# Generated by Django 4.2.13 on 2024-06-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0004_remove_user_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
