# Generated by Django 4.2.13 on 2024-06-01 20:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0005_user_is_staff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_staff",
        ),
    ]
