# Generated by Django 4.2.13 on 2024-06-02 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_alter_walkhistory_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='user',
        ),
    ]
